### PR TITLE
Clean up and update code

### PR DESCRIPTION
**Pull request by Briaoeuidhtns**
I switched to deps, a little simpler to work with than lein. Can be run instead with `clj -Arun`, which currently doesn't exist. The old main is under `clj -Apopulate-dev` and in dev resources.

I'll add tests, probably also needs some manual testing as I didn't do much.

### CODE REVIEW

**Comment by matthewReff** [comment]
Did you run the DB code on a live database? Some of the API names aren't the same as the corresponding DB column.

**Comment by Briaoeuidhtns** [comment]
I prob shouldn't have committed last night, I was too tired to actually run most of it.

The columns that are different get renamed with `rename-keys` tho, so you don't have to enumerate every key.

I'll add a docker image and at least a couple system tests in a bit

**Comment by Briaoeuidhtns** [comment]
ok, *now* I'm sure this is ready to merge

**Comment by Briaoeuidhtns** [comment]
CI fails during build, I think since I'm building off the dev branch of next-jdbc instead of from a published artifact, since that's really the only thing that changed there. I could look into fixing it, but it should have a new release soon enough so prob not worth it.

Far enough away from needing to build a release that this should be fine to merge.

I'll template out api stuff in another pr later, this has gotten messy enough...

**Comment by Briaoeuidhtns** [comment]
Nvm, fixed. May be worth looking at cambada alternatives, the fork was archived and the original repo looks pretty dead also

**Comment by Briaoeuidhtns** [comment]
merging to keep my sanity

**Pull request merged**
